Traceback (most recent call last):
  File "/mydata/flash/case-2-autoscaling/main.py", line 190, in <module>
    main(args.data_path, args.checkpoint_path, args.operation, args.model_dir, verbose=args.verbose)
  File "/mydata/flash/case-2-autoscaling/main.py", line 23, in main
    train(data_path, model_path)
  File "/mydata/flash/case-2-autoscaling/main.py", line 137, in train
    env = SimEnvironment(data_path)
  File "/mydata/flash/case-2-autoscaling/serverless_env.py", line 46, in __init__
    self.load_data()
  File "/mydata/flash/case-2-autoscaling/serverless_env.py", line 50, in load_data
    df = pd.read_csv(self.data_path)
  File "/users/yihanz8/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/users/yihanz8/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/users/yihanz8/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/users/yihanz8/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/users/yihanz8/.local/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../data-firm/decompress_compress_decompress_outpu.csv'
